on:
  workflow_dispatch:

name: rebuild-teams

jobs:
  rebuild-teams:
    name: rebuild-teams
    runs-on: ubuntu-teams
    env:
      GITHUB_PAT: ${{ secrets.CBBD_DATA_GH_TOKEN }}
      CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
      TO_UPDATE: ALL

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::httr
            any::RcppSimdJson
            any::data.table
            any::arrow
            any::qs
            any::piggyback
            any::gh
            any::janitor

      - name: Rebuild teams
        run: Rscript -e 'source("src/update-teams.R")'
