on:
  schedule:
    # runs every day at 8:10 AM UTC
    - cron:  '10 8 * 1,2,3,4,10,11,12 *'
  workflow_dispatch:

name: update-lines

jobs:
  update-lines:
    name: update-lines
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.CBBD_DATA_GH_TOKEN }}
      CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
      TO_UPDATE: MOST_REC

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::httr
            any::RcppSimdJson
            any::data.table
            any::arrow
            any::qs
            any::piggyback
            any::gh
            any::janitor
          extra-packages: |
            john-b-edwards/cbbreadr

      - name: Update lines
        run: Rscript -e 'source("src/update-lines.R")'
