on:
  workflow_dispatch:

name: update-player-box

jobs:
  update-player-box:
    name: update-player-box
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.CBBD_DATA_GH_TOKEN }}
      CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
      TO_UPDATE: MOST_REC

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::httr
            any::RcppSimdJson
            any::data.table
            any::arrow
            any::qs
            any::piggyback
            any::gh
            any::janitor

      - name: update player-box
        run: Rscript -e 'source("src/update-player-box.R")'
