on:
  schedule:
    # runs every day at 7:50 AM UTC
    - cron:  '50 7 * 1,2,3,4,10,11,12 *'
  workflow_dispatch:

name: update-player-stats

jobs:
  update-player-stats:
    name: update-player-stats
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.CBBD_DATA_GH_TOKEN }}
      CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
      TO_UPDATE: MOST_REC

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::httr
            any::RcppSimdJson
            any::data.table
            any::arrow
            any::qs
            any::piggyback
            any::gh
            any::janitor

      - name: update player-stats
        run: Rscript -e 'source("src/update-player-stats.R")'
